language: python
python:
- '3.5'
sudo: required
dist: xenial
before_install:
- sudo apt-get install libgnutls28-dev

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-4.3.27.1-Linux-x86_64.sh -O miniconda.sh
- export python_version=$TRAVIS_PYTHON_VERSION
- bash miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install conda=4.4.7
- conda env update -f environment.yml
- source activate virtual
- conda install -c omnia pdbfixer=1.4
- conda install -c deepchem mdtraj=1.9.1
- conda install -c rdkit rdkit=2017.09.1
- conda install -c conda-forge joblib=0.11 six=1.10.0 scikit-learn=0.19.1 keras=1.2.2 mdtraj=1.9.1 networkx=1.11 pandas=0.22.0 nose=1.3.7 nose-timer=0.7.0 flaky=3.3.0 zlib=1.2.11 requests=2.18.4 xgboost=0.6a2 simdna=0.4.2 jupyter=1.0.0 pbr=3.1.1
- pip install tensorflow==1.5.0
- pip install https://github.com/deepchem/deepchem/archive/2.0.0.tar.gz
- cd deepchem-2.0.0 && python setup.py install
- conda install -c r r-base r-bitops

script:
- pip list
- conda list
- nosetests -a '!slow' -v deepchem --nologcapture
